import type { Metadata } from 'next'
import './globals.css'
import i18nConfig from '@/libs/i18n/i18nConfig'
import { ReactNode } from 'react'
import initTranslations from '@/libs/i18n/i18n'
import { dir } from 'i18next'
import TranslationsProvider from '@/libs/i18n/TranslationsProvider'

import localFont from 'next/font/local'
import Footer from '@/components/footer/Footer'
import Header from '@/components/header/Header'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const playwrite = localFont({
    src: '../../../public/fonts/playwrite/PlaywriteAUQLD-Thin.ttf',
    display: 'swap',
    variable: '--font-playwrite',
})

const georgian = localFont({
    src: '../../../public/fonts/georgian/arial_geo-italic.ttf',
    display: 'swap',
    variable: '--font-georgian',
})

export function generateStaticParams() {
    return i18nConfig.locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
    children,
    params: { locale },
}: {
    children: ReactNode
    params: { locale: string }
}) {
    const i18nNamespaces = ['contact', 'main', 'repertory']
    const { resources } = await initTranslations(locale, i18nNamespaces)

    return (
        <html lang={locale} dir={dir(locale)}>
            <body className={`${georgian.variable} ${playwrite.variable}`}>
                <TranslationsProvider
                    namespaces={i18nNamespaces}
                    locale={locale}
                    resources={resources}
                >
                    <Header />
                    {children}
                    <Footer />
                </TranslationsProvider>
            </body>
        </html>
    )
}
